apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    categories: A list of comma separated categories that your operator falls under.
    certified: 'false'
    containerImage: quay.io/app-sre/aws-account-operator:latest
    createdAt: '2019-04-24T21:54:27Z'
    description: AWS account creator.
    support: James Harrington
  name: aws-account-operator.v0.1.102-e2b823c
  namespace: placeholder
spec:
  customresourcedefinitions:
    owned:
    - description: Reconcile AWS accounts ready for use.
      displayName: Account
      kind: Account
      name: accounts.aws.managed.openshift.io
      version: v1alpha1
    - description: Account Claims for reconciled AWS Accounts.
      displayName: Account Claim
      kind: AccountClaim
      name: accountclaims.aws.managed.openshift.io
      version: v1alpha1
    - description: Pool of unclaimed AWS Accounts.
      displayName: Account Pool
      kind: AccountPool
      name: accountpools.aws.managed.openshift.io
      version: v1alpha1
  description: AWS account creator.
  displayName: aws-account-operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ''
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ''
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - aws.managed.openshift.io
          resources:
          - '*'
          - accountclaims
          - accounts
          verbs:
          - '*'
        serviceAccountName: aws-account-operator
      - rules:
        - apiGroups:
          - aws.managed.openshift.io
          resources:
          - accountclaims
          verbs:
          - create
          - delete
          - get
          - list
          - watch
        serviceAccountName: aws-account-operator-client
      deployments:
      - name: aws-account-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: aws-account-operator
          template:
            metadata:
              labels:
                name: aws-account-operator
            spec:
              containers:
              - command:
                - aws-account-operator
                env:
                - name: WATCH_NAMESPACE
                  value: ''
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: aws-account-operator
                image: quay.io/app-sre/aws-account-operator:e2b823c
                imagePullPolicy: Always
                name: aws-account-operator
              serviceAccountName: aws-account-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - kubernetes
  - openshift
  - multi-cluster
  - cluster
  maturity: alpha
  provider:
    name: Red Hat, Inc
  replaces: aws-account-operator.v0.1.96-feb8807
  version: 0.1.102-e2b823c
